name: "authenticate-cross"
description: "cross"
author: cross
on:
 workflow_dispatch:
  inputs:
   username:
    description: "your github username"
    required: true
  reason:
    description: "the reason for the dispatch"
    required: true
    default: "I am runntin tests"

jobs:
 tests_manual_workflow:
  runs-on: ubuntu-latest
  steps:
  - run: >
     echo "User ${{github.event.inputs.username}} is running tests"
     echo "Reason: ${{github.event.inputs.reason}}"
